name: "Main Workflow"

on:
  push:
    branches:
      - master
  issues:
    types: [opened, edited, closed, reopened, deleted]
  issue_comment:
    types: [created, edited, deleted]
  workflow_dispatch:
    # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
#  schedule:
#    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: franzdiebold/github-env-vars-action@v2
      # https://github.com/marketplace/actions/github-environment-variables-action
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run endorsement --if-present
      env:
        ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run skill --if-present
      env:
        ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run recommendation --if-present
      env:
        ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run fame --if-present
      env:
        ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
