name: "Notification [ISSUE]"

on:
    issues:
        types: [ opened, edited ]

jobs:
    message:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: "Discord Notification - issue"
                uses: tsickert/discord-webhook@v5.3.0
                with:
                    webhook-url: "${{ secrets.WEBHOOK_URL }}"
                    embed-title: "${{ github.event.issue.title }} [${{ github.event.action }}]"
                    embed-description: "${{ github.event.issue.body }}"
                    embed-author-name: "${{ github.event.issue.user.login }}"
                    embed-author-url: "${{ github.event.issue.user.html_url }}"
                    embed-author-icon-url: "${{ github.event.issue.user.avatar_url }}"
